openapi: "3.0.3"
info:
  title: Auth Service Contract
  version: "0.1.0"
paths:
  /api/v1/auth/register:
    post:
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, password, username]
              properties:
                email: { type: string, format: email }
                password: { type: string, minLength: 8 }
                username: { type: string }
      responses:
        "201": { description: User created, returns user object + JWT }
        "409": { description: Email already registered }

  /api/v1/auth/login:
    post:
      summary: Login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [username, password]
              properties:
                username: { type: string }
                password: { type: string }
      responses:
        "200": { description: Returns access_token }
        "401": { description: Invalid credentials }

  /api/v1/auth/me:
    get:
      summary: Get current user
      security: [{ bearerAuth: [] }]
      responses:
        "200": { description: User object }

  /api/v1/auth/verify-email:
    get:
      summary: Verify email with token
      parameters:
        - name: token
          in: query
          required: true
          schema: { type: string }
      responses:
        "200": { description: Email verified }
        "400": { description: Invalid/expired token }

  /api/v1/auth/forgot-password:
    post:
      summary: Request password reset
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email: { type: string, format: email }
      responses:
        "200": { description: Reset email sent (always 200 to prevent enumeration) }

  /api/v1/auth/reset-password:
    post:
      summary: Reset password with token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [token, new_password]
              properties:
                token: { type: string }
                new_password: { type: string, minLength: 8 }
      responses:
        "200": { description: Password reset }
        "400": { description: Invalid/expired token }
